server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    basedir: /data/temp/tomcat

spring:
  servlet:
    multipart:
      max-file-size: 100
      max-request-size: 100
      location: /data/temp/tempFile